export const CATEGORIES = [
  { id: "tecnologia", label: "Tecnología", icon: "bx-devices" },
  { id: "hogar", label: "Hogar y Muebles", icon: "bx-home" },
  { id: "ropa", label: "Ropa y Accesorios", icon: "bx-closet" },
  { id: "juegos", label: "Juegos y Juguetes", icon: "bx-extension" },
  { id: "deportes", label: "Deportes y Fitness", icon: "bx-cycling" },
  { id: "calzado", label: "Calzado", icon: "bx-walk" },
  { id: "vehiculos", label: "Vehículos", icon: "bx-car" },
  { id: "herramientas", label: "Herramientas", icon: "bx-wrench" },
  { id: "libros", label: "Libros y Música", icon: "bx-book-open" },
  { id: "arte", label: "Arte y Hobbies", icon: "bx-palette" },
  { id: "coleccion", label: "Coleccionables", icon: "bx-crown" },
  { id: "servicios", label: "Servicios", icon: "bx-briefcase" },
  { id: "otros", label: "Otros", icon: "bx-dots-horizontal-rounded" },
];

export const CONDITIONS = [
  { id: "new", label: "Nuevo" },
  { id: "like_new", label: "Como nuevo" },
  { id: "good", label: "Buen estado" },
  { id: "fair", label: "Uso visible" },
];

export const PROVINCES = [
  "Buenos Aires",
  "CABA",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];
